# Python lists

In [1]:
li=[1,2,3,4,5,6,7]
print (li)

[1, 2, 3, 4, 5, 6, 7]


In [2]:
print(li[0:7])

[1, 2, 3, 4, 5, 6, 7]


In [3]:
print(li[0:8])

[1, 2, 3, 4, 5, 6, 7]


In [4]:
print(li[0:7:-1])

[]


In [5]:
print(li[0:7:1])
print(li[0:7:2])
print(li[0:7:3])

[1, 2, 3, 4, 5, 6, 7]
[1, 3, 5, 7]
[1, 4, 7]


In [6]:
print(li[7:0:-1])

[7, 6, 5, 4, 3, 2]


In [7]:
print(li[7:-1:-1])

[]


In [8]:
print(li[7::-1])

[7, 6, 5, 4, 3, 2, 1]


In [9]:
print(li[-1:-7])

[]


In [10]:
print(li[-1:-6])

[]


In [11]:
print(li[-1:-8])

[]


In [12]:
print(li[-1:-7:-1])

[7, 6, 5, 4, 3, 2]


In [13]:
print(li[-1::-1])

[7, 6, 5, 4, 3, 2, 1]


In [14]:
thislist = ["apple", "banana", "cherry"]
[print(x) for x in thislist]


apple
banana
cherry


[None, None, None]

In [15]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [x for x in fruits if "a" in x]

print(newlist)

['apple', 'banana', 'mango']


In [16]:
thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort(key = str.lower)
print(thislist)

['banana', 'cherry', 'Kiwi', 'Orange']


In [17]:
thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.reverse()
print(thislist)

['cherry', 'Kiwi', 'Orange', 'banana']


In [18]:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

list1.extend(list2)
print(list1)

['a', 'b', 'c', 1, 2, 3]


# Python Tuples

In [20]:
thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


In [21]:
thistuple = ("apple", "banana", "cherry")
print(len(thistuple))

3


In [22]:
thistuple = ("apple",)
print(type(thistuple))

#NOT a tuple
thistuple = ("apple")
print(type(thistuple))

<class 'tuple'>
<class 'str'>


In [23]:
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:])

('cherry', 'orange', 'kiwi', 'melon', 'mango')


In [24]:
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[-4:-1])

('orange', 'kiwi', 'melon')


In [25]:
thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
  print("Yes, 'apple' is in the fruits tuple")

Yes, 'apple' is in the fruits tuple


In [27]:
# Since Tuple is unchangable, we need to convert to list ...change it's element and then convert back to tuple
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

('apple', 'kiwi', 'cherry')


In [28]:
thistuple = ("apple", "banana", "cherry")
y = ("orange",)
thistuple += y

print(thistuple)

('apple', 'banana', 'cherry', 'orange')


In [29]:
fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)

apple
banana
cherry


In [30]:
fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")

(green, yellow, *red) = fruits

print(green)
print(yellow)
print(red)

apple
banana
['cherry', 'strawberry', 'raspberry']


In [31]:
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")

(green, *tropic, red) = fruits

print(green)
print(tropic)
print(red)

apple
['mango', 'papaya', 'pineapple']
cherry


In [32]:
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)

apple
banana
cherry


In [33]:
thistuple = ("apple", "banana", "cherry")
for i in range(len(thistuple)):
  print(thistuple[i])

apple
banana
cherry


In [34]:
thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple):
  print(thistuple[i])
  i = i + 1

apple
banana
cherry


In [35]:
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)

('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')


# Python Sets

In [37]:
thisset = {"apple", "banana", "cherry"}
print(thisset)

{'apple', 'banana', 'cherry'}


In [38]:
thisset = {"apple", "banana", "cherry", "apple"}

print(thisset)

{'apple', 'banana', 'cherry'}


In [39]:
set1 = {"abc", 34, True, 40, "male"}
print(set1)

{True, 34, 'male', 40, 'abc'}


In [40]:
thisset = {"apple", "banana", "cherry"}

thisset.add("orange")

print(thisset)

{'apple', 'banana', 'orange', 'cherry'}


In [42]:
thisset = {"apple", "banana", "cherry"}
mylist = ["kiwi", "orange"]

thisset.update(mylist)

print(thisset)

{'apple', 'cherry', 'banana', 'kiwi', 'orange'}


In [43]:
thisset = {"apple", "banana", "cherry"}

thisset.remove("banana")

print(thisset)

{'apple', 'cherry'}


In [44]:
thisset = {"apple", "banana", "cherry"}

del thisset

print(thisset)

NameError: name 'thisset' is not defined

In [45]:
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)

{1, 2, 3, 'b', 'a', 'c'}


In [46]:
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set1.update(set2)
print(set1)

{1, 2, 3, 'b', 'a', 'c'}


In [47]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.intersection_update(y)

print(x)

{'apple'}


In [48]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.symmetric_difference_update(y)

print(x)

{'microsoft', 'google', 'cherry', 'banana'}


# Python Dictionaries

In [49]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [52]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["year"])
print(len(thisdict))

1964
3


In [54]:
thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}
print(thisdict["year"])
print(len(thisdict))

1964
4


In [56]:
x = thisdict.keys()
print(x)

dict_keys(['brand', 'electric', 'year', 'colors'])


In [57]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.keys()

print(x) #before the change

car["color"] = "white"

print(x) #after the change

dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])


In [58]:
x = thisdict.values()
print(x)

dict_values(['Ford', False, 1964, ['red', 'white', 'blue']])


In [59]:
x = thisdict.items()
print(x)

dict_items([('brand', 'Ford'), ('electric', False), ('year', 1964), ('colors', ['red', 'white', 'blue'])])


In [60]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
if "model" in thisdict:
  print("Yes, 'model' is one of the keys in the thisdict dictionary")

Yes, 'model' is one of the keys in the thisdict dictionary


In [61]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.pop("model")
print(thisdict)

{'brand': 'Ford', 'year': 1964}


In [62]:
for x in thisdict:
  print(thisdict[x])

Ford
1964


In [63]:
for x, y in thisdict.items():
  print(x, y)

brand Ford
year 1964


In [64]:
child1 = {
  "name" : "Emil",
  "year" : 2004
}
child2 = {
  "name" : "Tobias",
  "year" : 2007
}
child3 = {
  "name" : "Linus",
  "year" : 2011
}

myfamily = {
  "child1" : child1,
  "child2" : child2,
  "child3" : child3
}
print(myfamily)

{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2007}, 'child3': {'name': 'Linus', 'year': 2011}}


# Python Loops and iterators

In [66]:
for x in range(6):
  print(x)

0
1
2
3
4
5


# Python Strings

In [67]:
a = '''Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.'''
print(a)

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.


In [68]:
a = "Hello, World!"
print(a[1])

e


In [69]:
txt = "The best things in life are free!"
if "free" in txt:
  print("Yes, 'free' is present.")

Yes, 'free' is present.


In [70]:
txt = "The best things in life are free!"
print("expensive" not in txt)

True


In [71]:
b = "Hello, World!"
print(b[2:5])

llo


In [72]:
b = "Hello, World!"
print(b[-5:-2])

orl


In [75]:
a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"


Hello, World!


In [76]:
a = "Hello, World!"
print(a.replace("H", "J"))

Jello, World!


In [77]:
a = "Hello, World!"
print(a.split(",")) # returns ['Hello', ' World!']

['Hello', ' World!']


In [79]:
age = 36
txt = "My name is John, and I am {}".format(age)
print(txt)

My name is John, and I am 36


In [80]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want {} pieces of item {} for {} dollars."
print(myorder.format(quantity, itemno, price))

I want 3 pieces of item 567 for 49.95 dollars.


In [81]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

I want to pay 49.95 dollars for 3 pieces of item 567.


In [82]:
txt = "We are the so-called \"Vikings\" from the north."
txt

'We are the so-called "Vikings" from the north.'

In [83]:
print(txt)

We are the so-called "Vikings" from the north.


# Python Conditional Statements

In [84]:
a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a and b are equal


In [85]:
if a > b: print("a is greater than b")

In [86]:
a = 2
b = 330
print("A") if a > b else print("B")

B


In [87]:
a = 330
b = 330
print("A") if a > b else print("=") if a == b else print("B")

=


In [88]:
a = 33
b = 200

if b > a:
  pass

# Python Numpy array 

In [89]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [90]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [91]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [94]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [95]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [96]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [97]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [98]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [99]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [100]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [101]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [102]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [103]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [104]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [105]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [106]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [107]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [108]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [109]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [110]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [111]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Flattening an array 

In [112]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [113]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [114]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [115]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [116]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [117]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [118]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [119]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [120]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [121]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [122]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [123]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [124]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [125]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [126]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [127]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [128]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [129]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [130]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [131]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [132]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [133]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [134]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [135]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [136]:
from numpy import random

x = random.randint(100)

print(x)

90


# Pandas DataFrame

In [137]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [139]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


In [140]:
print(myvar[0])

1


In [141]:


a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64


In [142]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [143]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df) 

   calories  duration
0       420        50
1       380        40
2       390        45


In [144]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64


In [145]:
#use a list of indexes:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40


# Working with Boston Dataset

In [2]:
import pandas as pd
df=pd.read_csv('boston.csv')

df.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2

In [3]:
df.loc[0,"nox"]

0.538

In [20]:
df.shape

(506, 15)

In [4]:
df.loc[0:5,"nox"]

0    0.538
1    0.469
2    0.469
3    0.458
4    0.458
5    0.458
Name: nox, dtype: float64

In [9]:
df.loc[0:10,"crim":"age"].head()

crim    zn  indus  chas    nox     rm   age
0  0.00632  18.0   2.31     0  0.538  6.575  65.2
1  0.02731   0.0   7.07     0  0.469  6.421  78.9
2  0.02729   0.0   7.07     0  0.469  7.185  61.1
3  0.03237   0.0   2.18     0  0.458  6.998  45.8
4  0.06905   0.0   2.18     0  0.458  7.147  54.2

In [13]:
df.loc[0:3,["crim","chas","nox"]]

crim  chas    nox
0  0.00632     0  0.538
1  0.02731     0  0.469
2  0.02729     0  0.469
3  0.03237     0  0.458

In [15]:
df.loc[:,["crim","chas"]]

crim  chas
0    0.00632     0
1    0.02731     0
2    0.02729     0
3    0.03237     0
4    0.06905     0
..       ...   ...
501  0.06263     0
502  0.04527     0
503  0.06076     0
504  0.10959     0
505  0.04741     0

[506 rows x 2 columns]

In [22]:
df.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2

In [21]:
df.iloc[1,3]

7.07

In [30]:
rad3=df[df['rad']==3]
print(rad3.shape)
rad3.head()

(38, 15)


Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
3            4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4            5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   
5            6  0.02985   0.0   2.18     0  0.458  6.430  58.7  6.0622    3   
39          40  0.02763  75.0   2.95     0  0.428  6.595  21.8  5.4011    3   
40          41  0.03359  75.0   2.95     0  0.428  7.024  15.8  5.4011    3   

    tax  ptratio   black  lstat  medv  
3   222     18.7  394.63   2.94  33.4  
4   222     18.7  396.90   5.33  36.2  
5   222     18.7  394.12   5.21  28.7  
39  252     18.3  395.63   4.32  30.8  
40  252     18.3  395.62   1.98  34.9

In [37]:
nox=rad3.nox
rad3.head()

Unnamed: 0     crim    zn  indus  chas   nox     rm   age     dis  rad  \
3            4  0.03237   0.0   2.18     0  45.8  6.998  45.8  6.0622    3   
4            5  0.06905   0.0   2.18     0  45.8  7.147  54.2  6.0622    3   
5            6  0.02985   0.0   2.18     0  45.8  6.430  58.7  6.0622    3   
39          40  0.02763  75.0   2.95     0  42.8  6.595  21.8  5.4011    3   
40          41  0.03359  75.0   2.95     0  42.8  7.024  15.8  5.4011    3   

    tax  ptratio   black  lstat  medv  
3   222     18.7  394.63   2.94  33.4  
4   222     18.7  396.90   5.33  36.2  
5   222     18.7  394.12   5.21  28.7  
39  252     18.3  395.63   4.32  30.8  
40  252     18.3  395.62   1.98  34.9

In [38]:
df.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2

In [39]:
tax300=df[df['tax']>300]
tax300.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm    age     dis  rad  \
6            7  0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5   
7            8  0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5   
8            9  0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5   
9           10  0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5   
10          11  0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5   

    tax  ptratio   black  lstat  medv  
6   311     15.2  395.60  12.43  22.9  
7   311     15.2  396.90  19.15  27.1  
8   311     15.2  386.63  29.93  16.5  
9   311     15.2  386.71  17.10  18.9  
10  311     15.2  392.52  20.45  15.0

In [43]:
tax300.loc[1,3]='null'

In [44]:
tax300.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm    age     dis  rad  \
6          7.0  0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0   
7          8.0  0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0   
8          9.0  0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0   
9         10.0  0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0   
10        11.0  0.22489  12.5   7.87   0.0  0.524  6.377   94.3  6.3467  5.0   

      tax  ptratio   black  lstat  medv    3  
6   311.0     15.2  395.60  12.43  22.9  NaN  
7   311.0     15.2  396.90  19.15  27.1  NaN  
8   311.0     15.2  386.63  29.93  16.5  NaN  
9   311.0     15.2  386.71  17.10  18.9  NaN  
10  311.0     15.2  392.52  20.45  15.0  NaN

In [46]:
tax300.columns

Index(['Unnamed: 0',       'crim',         'zn',      'indus',       'chas',
              'nox',         'rm',        'age',        'dis',        'rad',
              'tax',    'ptratio',      'black',      'lstat',       'medv',
                  3],
      dtype='object')

In [55]:
tax300.drop(columns='Unnamed: 0',inplace=True)
tax300.head()

crim    zn  indus  chas    nox     rm    age     dis  rad    tax  \
6   0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7   0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9   0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   
10  0.22489  12.5   7.87   0.0  0.524  6.377   94.3  6.3467  5.0  311.0   

    ptratio   black  lstat  medv  
6      15.2  395.60  12.43  22.9  
7      15.2  396.90  19.15  27.1  
8      15.2  386.63  29.93  16.5  
9      15.2  386.71  17.10  18.9  
10     15.2  392.52  20.45  15.0

In [56]:
df.head()

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   

   tax  ptratio   black  lstat  medv  
0  296     15.3  396.90   4.98  24.0  
1  242     17.8  396.90   9.14  21.6  
2  242     17.8  392.83   4.03  34.7  
3  222     18.7  394.63   2.94  33.4  
4  222     18.7  396.90   5.33  36.2

In [57]:
df.drop(columns='Unnamed: 0',inplace = True)
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [58]:
tax300.head()

crim    zn  indus  chas    nox     rm    age     dis  rad    tax  \
6   0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7   0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9   0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   
10  0.22489  12.5   7.87   0.0  0.524  6.377   94.3  6.3467  5.0  311.0   

    ptratio   black  lstat  medv  
6      15.2  395.60  12.43  22.9  
7      15.2  396.90  19.15  27.1  
8      15.2  386.63  29.93  16.5  
9      15.2  386.71  17.10  18.9  
10     15.2  392.52  20.45  15.0

In [59]:
tax300['medv_rank']=tax300.medv.rank()

In [60]:
tax300

crim    zn  indus  chas    nox     rm    age     dis  rad    tax  \
6    0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7    0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8    0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9    0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   
10   0.22489  12.5   7.87   0.0  0.524  6.377   94.3  6.3467  5.0  311.0   
..       ...   ...    ...   ...    ...    ...    ...     ...  ...    ...   
497  0.26838   0.0   9.69   0.0  0.585  5.794   70.6  2.8927  6.0  391.0   
498  0.23912   0.0   9.69   0.0  0.585  6.019   65.3  2.4091  6.0  391.0   
499  0.17783   0.0   9.69   0.0  0.585  5.569   73.5  2.3999  6.0  391.0   
500  0.22438   0.0   9.69   0.0  0.585  6.027   79.7  2.4982  6.0  391.0   
1        NaN   NaN    NaN   NaN    NaN    NaN    NaN     NaN  NaN    NaN   

     ptratio   black  lstat  medv  medv_rank  
6       15.2  395.60  12.43  22.9      246.5  
7       15.2  396.90  19.15  27.1      289.0  
8       15.2  386.63  29.93  16.5      115.5  
9       15.2  386.71  17.10  18.9      160.0  
10      15.2  392.52  20.45  15.0       94.0  
..       ...     ...    ...   ...        ...  
497     19.2  396.90  14.10  18.3      148.5  
498     19.2  396.90  12.92  21.2      216.5  
499     19.2  395.77  15.10  17.5      133.0  
500     19.2  396.90  14.33  16.8      120.5  
1        NaN     NaN    NaN   NaN        NaN  

[335 rows x 15 columns]

In [61]:
tax300.dropna(how="all",axis=0,inplace = True)
tax300

crim    zn  indus  chas    nox     rm    age     dis  rad    tax  \
6    0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7    0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8    0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9    0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   
10   0.22489  12.5   7.87   0.0  0.524  6.377   94.3  6.3467  5.0  311.0   
..       ...   ...    ...   ...    ...    ...    ...     ...  ...    ...   
496  0.28960   0.0   9.69   0.0  0.585  5.390   72.9  2.7986  6.0  391.0   
497  0.26838   0.0   9.69   0.0  0.585  5.794   70.6  2.8927  6.0  391.0   
498  0.23912   0.0   9.69   0.0  0.585  6.019   65.3  2.4091  6.0  391.0   
499  0.17783   0.0   9.69   0.0  0.585  5.569   73.5  2.3999  6.0  391.0   
500  0.22438   0.0   9.69   0.0  0.585  6.027   79.7  2.4982  6.0  391.0   

     ptratio   black  lstat  medv  medv_rank  
6       15.2  395.60  12.43  22.9      246.5  
7       15.2  396.90  19.15  27.1      289.0  
8       15.2  386.63  29.93  16.5      115.5  
9       15.2  386.71  17.10  18.9      160.0  
10      15.2  392.52  20.45  15.0       94.0  
..       ...     ...    ...   ...        ...  
496     19.2  396.90  21.14  19.7      184.0  
497     19.2  396.90  14.10  18.3      148.5  
498     19.2  396.90  12.92  21.2      216.5  
499     19.2  395.77  15.10  17.5      133.0  
500     19.2  396.90  14.33  16.8      120.5  

[334 rows x 15 columns]

In [62]:
tax300=tax300.sort_values(['medv_rank']).reset_index(drop=True)
tax300

crim   zn  indus  chas    nox     rm    age     dis   rad    tax  \
0    38.35180  0.0  18.10   0.0  0.693  5.453  100.0  1.4896  24.0  666.0   
1    67.92080  0.0  18.10   0.0  0.693  5.683  100.0  1.4254  24.0  666.0   
2    25.04610  0.0  18.10   0.0  0.693  5.987  100.0  1.5888  24.0  666.0   
3     9.91655  0.0  18.10   0.0  0.693  5.852   77.8  1.5004  24.0  666.0   
4     0.18337  0.0  27.74   0.0  0.609  5.414   98.3  1.7554   4.0  711.0   
..        ...  ...    ...   ...    ...    ...    ...     ...   ...    ...   
329   5.66998  0.0  18.10   1.0  0.631  6.683   96.8  1.3567  24.0  666.0   
330   6.53876  0.0  18.10   1.0  0.631  7.016   97.5  1.2024  24.0  666.0   
331   9.23230  0.0  18.10   0.0  0.631  6.216  100.0  1.1691  24.0  666.0   
332   8.26725  0.0  18.10   1.0  0.668  5.875   89.6  1.1296  24.0  666.0   
333   1.46336  0.0  19.58   0.0  0.605  7.489   90.8  1.9709   5.0  403.0   

     ptratio   black  lstat  medv  medv_rank  
0       20.2  396.90  30.59   5.0        1.5  
1       20.2  384.97  22.98   5.0        1.5  
2       20.2  396.90  26.77   5.6        3.0  
3       20.2  338.16  29.97   6.3        4.0  
4       20.1  344.05  23.97   7.0        5.5  
..       ...     ...    ...   ...        ...  
329     20.2  375.33   3.73  50.0      329.5  
330     20.2  392.05   2.96  50.0      329.5  
331     20.2  366.15   9.53  50.0      329.5  
332     20.2  347.88   8.88  50.0      329.5  
333     14.7  374.43   1.73  50.0      329.5  

[334 rows x 15 columns]

In [65]:
rm=pd.concat([tax300['medv'],tax300['medv_rank']],axis=1)
rm.head()

medv  medv_rank
0   5.0        1.5
1   5.0        1.5
2   5.6        3.0
3   6.3        4.0
4   7.0        5.5

# Working with Santander Dataset

In [67]:
dfs=pd.read_csv('santander.csv')
dfs.head()

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0   1     2     23                 0.0                      0.0   
1   3     2     34                 0.0                      0.0   
2   4     2     23                 0.0                      0.0   
3   8     2     37                 0.0                    195.0   
4  10     2     39                 0.0                      0.0   

   imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                    195.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  ...  \
0                      0.0                      0.0  ...   
1                      0.0                      0.0  ...   
2                      0.0                      0.0  ...   
3                      0.0                      0.0  ...   
4                      0.0                      0.0  ...   

   saldo_medio_var33_hace2  saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
0                      0.0                      0.0                     0.0   
1                      0.0                      0.0                     0.0   
2                      0.0                      0.0                     0.0   
3                      0.0                      0.0                     0.0   
4                      0.0                      0.0                     0.0   

   saldo_medio_var33_ult3  saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
0                     0.0                      0.0                      0.0   
1                     0.0                      0.0                      0.0   
2                     0.0                      0.0                      0.0   
3                     0.0                      0.0                      0.0   
4                     0.0                      0.0                      0.0   

   saldo_medio_var44_ult1  saldo_medio_var44_ult3          var38  TARGET  
0                     0.0                     0.0   39205.170000       0  
1                     0.0                     0.0   49278.030000       0  
2                     0.0                     0.0   67333.770000       0  
3                     0.0                     0.0   64007.970000       0  
4                     0.0                     0.0  117310.979016       0  

[5 rows x 371 columns]

In [69]:
[col for col in dfs.columns if dfs[col].isnull().sum()>0]

[]

In [70]:
from sklearn.model_selection import train_test_split
# separate train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(dfs.drop(labels=['TARGET'],axis=1),dfs['TARGET'],test_size=0.3,random_state=0)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(53214, 370)
(53214,)
(22806, 370)
(22806,)


In [72]:
#we'll transpose the dataset so that we can see which columns are duplicate
data_t=X_train.T
data_t.head()

7526      51929    46677    46194     20190  \
ID                       15083.0  103706.0  93351.0  92424.0  40437.00   
var3                         2.0       2.0      2.0      2.0      2.00   
var15                       23.0      48.0     40.0     83.0     79.00   
imp_ent_var16_ult1           0.0       0.0      0.0      0.0      0.00   
imp_op_var39_comer_ult1      0.0       0.0      0.0      0.0    535.41   

                           10777     57058    40266     75243     50225  ...  \
ID                       21599.0  113842.0  80549.0  150235.0  100282.0  ...   
var3                         2.0       2.0      2.0       2.0       2.0  ...   
var15                       23.0      23.0     24.0      42.0      64.0  ...   
imp_ent_var16_ult1           0.0       0.0      0.0       0.0       0.0  ...   
imp_op_var39_comer_ult1      0.0       0.0      0.0       0.0       0.0  ...   

                            52620    39512    48600     55026    41993  \
ID                       105033.0  79105.0  97108.0  109781.0  84101.0   
var3                          2.0      2.0      2.0       2.0      2.0   
var15                        26.0     28.0     25.0      33.0     23.0   
imp_ent_var16_ult1            0.0      0.0      0.0       0.0      0.0   
imp_op_var39_comer_ult1       0.0      0.0      0.0       0.0      0.0   

                            21243    45891    42613     43567     68268  
ID                       42533.00  91801.0  85345.0  87270.00  136296.0  
var3                        53.00      2.0      9.0      2.00       2.0  
var15                       46.00     29.0     23.0     30.00      55.0  
imp_ent_var16_ult1           0.00      0.0      0.0     60.00       0.0  
imp_op_var39_comer_ult1   1770.48      0.0      0.0     72.48       0.0  

[5 rows x 53214 columns]

In [73]:
data_t.duplicated().sum()

65

In [74]:
data_t[data_t.duplicated()]

7526   51929  46677  46194  20190  10777  \
ind_var2                         0.0    0.0    0.0    0.0    0.0    0.0   
ind_var13_medio                  0.0    0.0    0.0    0.0    0.0    0.0   
ind_var18                        0.0    0.0    0.0    0.0    0.0    0.0   
ind_var26                        0.0    0.0    0.0    0.0    0.0    0.0   
ind_var25                        0.0    0.0    0.0    0.0    0.0    0.0   
...                              ...    ...    ...    ...    ...    ...   
num_trasp_var17_out_hace3        0.0    0.0    0.0    0.0    0.0    0.0   
num_trasp_var33_out_hace3        0.0    0.0    0.0    0.0    0.0    0.0   
saldo_var2_ult1                  0.0    0.0    0.0    0.0    0.0    0.0   
saldo_medio_var13_medio_hace3    0.0    0.0    0.0    0.0    0.0    0.0   
saldo_medio_var13_medio_ult1     0.0    0.0    0.0    0.0    0.0    0.0   

                               57058  40266  75243  50225  ...  52620  39512  \
ind_var2                         0.0    0.0    0.0    0.0  ...    0.0    0.0   
ind_var13_medio                  0.0    0.0    0.0    0.0  ...    0.0    0.0   
ind_var18                        0.0    0.0    0.0    0.0  ...    0.0    0.0   
ind_var26                        0.0    0.0    0.0    0.0  ...    0.0    0.0   
ind_var25                        0.0    0.0    0.0    0.0  ...    0.0    0.0   
...                              ...    ...    ...    ...  ...    ...    ...   
num_trasp_var17_out_hace3        0.0    0.0    0.0    0.0  ...    0.0    0.0   
num_trasp_var33_out_hace3        0.0    0.0    0.0    0.0  ...    0.0    0.0   
saldo_var2_ult1                  0.0    0.0    0.0    0.0  ...    0.0    0.0   
saldo_medio_var13_medio_hace3    0.0    0.0    0.0    0.0  ...    0.0    0.0   
saldo_medio_var13_medio_ult1     0.0    0.0    0.0    0.0  ...    0.0    0.0   

                               48600  55026  41993  21243  45891  42613  \
ind_var2                         0.0    0.0    0.0    0.0    0.0    0.0   
ind_var13_medio                  0.0    0.0    0.0    0.0    0.0    0.0   
ind_var18                        0.0    0.0    0.0    0.0    0.0    0.0   
ind_var26                        0.0    1.0    0.0    0.0    0.0    0.0   
ind_var25                        0.0    1.0    0.0    0.0    0.0    0.0   
...                              ...    ...    ...    ...    ...    ...   
num_trasp_var17_out_hace3        0.0    0.0    0.0    0.0    0.0    0.0   
num_trasp_var33_out_hace3        0.0    0.0    0.0    0.0    0.0    0.0   
saldo_var2_ult1                  0.0    0.0    0.0    0.0    0.0    0.0   
saldo_medio_var13_medio_hace3    0.0    0.0    0.0    0.0    0.0    0.0   
saldo_medio_var13_medio_ult1     0.0    0.0    0.0    0.0    0.0    0.0   

                               43567  68268  
ind_var2                         0.0    0.0  
ind_var13_medio                  0.0    0.0  
ind_var18                        0.0    0.0  
ind_var26                        0.0    0.0  
ind_var25                        0.0    0.0  
...                              ...    ...  
num_trasp_var17_out_hace3        0.0    0.0  
num_trasp_var33_out_hace3        0.0    0.0  
saldo_var2_ult1                  0.0    0.0  
saldo_medio_var13_medio_hace3    0.0    0.0  
saldo_medio_var13_medio_ult1     0.0    0.0  

[65 rows x 53214 columns]

In [76]:
# We can capture the duplicated features, bu capturing the index 
# values of the transposed dataframe like this

duplicated_features = data_t[data_t.duplicated()].index.values
duplicated_features

array(['ind_var2', 'ind_var13_medio', 'ind_var18', 'ind_var26',
       'ind_var25', 'ind_var27_0', 'ind_var28_0', 'ind_var28',
       'ind_var27', 'ind_var29_0', 'ind_var29', 'ind_var32', 'ind_var34',
       'ind_var37', 'ind_var41', 'ind_var39', 'ind_var46_0', 'ind_var46',
       'num_var13_medio', 'num_var18', 'num_var26', 'num_var25',
       'num_var27_0', 'num_var28_0', 'num_var28', 'num_var27',
       'num_var29_0', 'num_var29', 'num_var32', 'num_var34', 'num_var37',
       'num_var41', 'num_var39', 'num_var46_0', 'num_var46',
       'saldo_var28', 'saldo_var27', 'saldo_var29', 'saldo_var41',
       'saldo_var46', 'delta_imp_reemb_var33_1y3',
       'delta_num_reemb_var13_1y3', 'delta_num_reemb_var17_1y3',
       'delta_num_reemb_var33_1y3', 'delta_num_trasp_var17_in_1y3',
       'delta_num_trasp_var17_out_1y3', 'delta_num_trasp_var33_in_1y3',
       'delta_num_trasp_var33_out_1y3', 'imp_amort_var18_hace3',
       'imp_amort_var34_hace3', 'imp_reemb_var13_hace3',
       'imp_reemb

In [78]:
# alternatively, we can remove the duplicated rows, 
# transpose the dataframe back to the variables as columns
# keep first indicates that we keep the first os a set of duplicated variables

data_unique = data_t.drop_duplicates(keep='first').T
data_unique.shape

(53214, 305)

In [79]:
data_unique.head()

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
7526    15083.0   2.0   23.0                 0.0                     0.00   
51929  103706.0   2.0   48.0                 0.0                     0.00   
46677   93351.0   2.0   40.0                 0.0                     0.00   
46194   92424.0   2.0   83.0                 0.0                     0.00   
20190   40437.0   2.0   79.0                 0.0                   535.41   

       imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  \
7526                      0.00                      0.0   
51929                     0.00                      0.0   
46677                     0.00                      0.0   
46194                     0.00                      0.0   
20190                   535.41                      0.0   

       imp_op_var40_comer_ult3  imp_op_var40_efect_ult1  \
7526                       0.0                      0.0   
51929                      0.0                      0.0   
46677                      0.0                      0.0   
46194                      0.0                      0.0   
20190                      0.0                      0.0   

       imp_op_var40_efect_ult3  ...  saldo_medio_var29_ult3  \
7526                       0.0  ...                     0.0   
51929                      0.0  ...                     0.0   
46677                      0.0  ...                     0.0   
46194                      0.0  ...                     0.0   
20190                      0.0  ...                     0.0   

       saldo_medio_var33_hace2  saldo_medio_var33_hace3  \
7526                       0.0                      0.0   
51929                      0.0                      0.0   
46677                      0.0                      0.0   
46194                      0.0                      0.0   
20190                      0.0                      0.0   

       saldo_medio_var33_ult1  saldo_medio_var33_ult3  \
7526                      0.0                     0.0   
51929                     0.0                     0.0   
46677                     0.0                     0.0   
46194                     0.0                     0.0   
20190                     0.0                     0.0   

       saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
7526                       0.0                      0.0   
51929                      0.0                      0.0   
46677                      0.0                      0.0   
46194                      0.0                      0.0   
20190                      0.0                      0.0   

       saldo_medio_var44_ult1  saldo_medio_var44_ult3          var38  
7526                      0.0                     0.0  117310.979016  
51929                     0.0                     0.0  451931.220000  
46677                     0.0                     0.0   41225.670000  
46194                     0.0                     0.0  117310.979016  
20190                     0.0                     0.0  153477.690000  

[5 rows x 305 columns]

# Python Date and Time

In [80]:
import datetime
print("import successful")

import successful


In [82]:
data=pd.read_csv('train.csv')
data.head()

UniqueID  disbursed_amount  asset_cost    ltv  branch_id  supplier_id  \
0    420825             50578       58400  89.55         67        22807   
1    537409             47145       65550  73.23         67        22807   
2    417566             53278       61360  89.63         67        22807   
3    624493             57513       66113  88.48         67        22807   
4    539055             52378       60300  88.39         67        22807   

   manufacturer_id  Current_pincode_ID Date.of.Birth Employment.Type  ...  \
0               45                1441      01-01-84        Salaried  ...   
1               45                1502      31-07-85   Self employed  ...   
2               45                1497      24-08-85   Self employed  ...   
3               45                1501      30-12-93   Self employed  ...   
4               45                1495      09-12-77   Self employed  ...   

  SEC.SANCTIONED.AMOUNT  SEC.DISBURSED.AMOUNT  PRIMARY.INSTAL.AMT  \
0                     0                     0                   0   
1                     0                     0                1991   
2                     0                     0                   0   
3                     0                     0                  31   
4                     0                     0                   0   

   SEC.INSTAL.AMT  NEW.ACCTS.IN.LAST.SIX.MONTHS  \
0               0                             0   
1               0                             0   
2               0                             0   
3               0                             0   
4               0                             0   

   DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS  AVERAGE.ACCT.AGE  \
0                                    0         0yrs 0mon   
1                                    1        1yrs 11mon   
2                                    0         0yrs 0mon   
3                                    0         0yrs 8mon   
4                                    0         0yrs 0mon   

   CREDIT.HISTORY.LENGTH  NO.OF_INQUIRIES  loan_default  
0              0yrs 0mon                0             0  
1             1yrs 11mon                0             1  
2              0yrs 0mon                0             0  
3              1yrs 3mon                1             1  
4              0yrs 0mon                1             1  

[5 rows x 41 columns]

In [83]:
data.columns

Index(['UniqueID', 'disbursed_amount', 'asset_cost', 'ltv', 'branch_id',
       'supplier_id', 'manufacturer_id', 'Current_pincode_ID', 'Date.of.Birth',
       'Employment.Type', 'DisbursalDate', 'State_ID', 'Employee_code_ID',
       'MobileNo_Avl_Flag', 'Aadhar_flag', 'PAN_flag', 'VoterID_flag',
       'Driving_flag', 'Passport_flag', 'PERFORM_CNS.SCORE',
       'PERFORM_CNS.SCORE.DESCRIPTION', 'PRI.NO.OF.ACCTS', 'PRI.ACTIVE.ACCTS',
       'PRI.OVERDUE.ACCTS', 'PRI.CURRENT.BALANCE', 'PRI.SANCTIONED.AMOUNT',
       'PRI.DISBURSED.AMOUNT', 'SEC.NO.OF.ACCTS', 'SEC.ACTIVE.ACCTS',
       'SEC.OVERDUE.ACCTS', 'SEC.CURRENT.BALANCE', 'SEC.SANCTIONED.AMOUNT',
       'SEC.DISBURSED.AMOUNT', 'PRIMARY.INSTAL.AMT', 'SEC.INSTAL.AMT',
       'NEW.ACCTS.IN.LAST.SIX.MONTHS', 'DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS',
       'AVERAGE.ACCT.AGE', 'CREDIT.HISTORY.LENGTH', 'NO.OF_INQUIRIES',
       'loan_default'],
      dtype='object')

In [85]:
data=data[['Date.of.Birth','DisbursalDate']]
data.head()

Date.of.Birth DisbursalDate
0      01-01-84      03-08-18
1      31-07-85      26-09-18
2      24-08-85      01-08-18
3      30-12-93      26-10-18
4      09-12-77      26-09-18

In [86]:
data.dtypes

Date.of.Birth    object
DisbursalDate    object
dtype: object

In [92]:
#We'll convert these datatypes to datetime

In [88]:
data['Date.of.Birth']=pd.to_datetime(data['Date.of.Birth'])
data['Date.of.Birth'].dtype

dtype('<M8[ns]')

In [90]:
data.dtypes

Date.of.Birth    datetime64[ns]
DisbursalDate            object
dtype: object

In [91]:
data['DisbursalDate']=pd.to_datetime(data['DisbursalDate'])
data.dtypes

Date.of.Birth    datetime64[ns]
DisbursalDate    datetime64[ns]
dtype: object

In [100]:
data.head()

Date.of.Birth DisbursalDate
0    1984-01-01    2018-03-08
1    1985-07-31    2018-09-26
2    1985-08-24    2018-01-08
3    1993-12-30    2018-10-26
4    1977-09-12    2018-09-26

In [102]:
# Month from date
data['month']=data['Date.of.Birth'].dt.month
data[['Date.of.Birth','month']].head()

Date.of.Birth  month
0    1984-01-01      1
1    1985-07-31      7
2    1985-08-24      8
3    1993-12-30     12
4    1977-09-12      9

In [103]:
# Similarly year from date , day from date.

In [104]:
#similarly quarter, dayofweek, weekday_name, is_in, datetime.now() etc